### ISSUE TITLE
Hurdles in completing quickstart, lustre_http dependency version conflict

### ISSUE THREAD

**Issue by jamesearl** [lustre-labs/lustre#210]
I was trying to run through the quickstart for v4.6.1 found at https://hexdocs.pm/lustre/guide/01-quickstart.html.

I'm got to the section titled "Talking to the outside world". When running the command 
```bash
$ gleam add lustre_http
```

I hit this error:
```text
  Resolving versions
error: Dependency resolution failed

An error occurred while determining what dependency packages and
versions should be downloaded.
The error from the version resolver library was:

Unable to find compatible versions for the version constraints in your
gleam.toml. The conflicting packages are:

- lustre
- test_gleam_quickstart
- lustre_http
- gleam_json

```

This was my gleam.toml when reaching that step of the quickstart:
```toml
name = "test_gleam_quickstart"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.6.1 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.0 and < 2.0.0"
```

This is my working environment
```text
erlang
 *27.1.2
gleam
 *1.5.1
rebar
 *3.24.0
```
